Repository openshift-psap/ci-artifacts, pull requests merged in 2021-05, with the labels that each got.

#141 entitlement_deploy: use ignition v3.0.0 for compatibility with OCP 4.5 and 4.6
  roles/entitlement_deploy/files/mc_pem.yml
  roles/entitlement_deploy/files/mc_rhsm.yml
Labels: approved, lgtm

#138 build/Dockerfile: install rsync for oc adm must-gather
  build/Dockerfile
Labels: approved, lgtm

#142 build: make cluster_run_libs.sh executable
  build/root/var/lib/ci-artifacts/entrypoints.d/cluster_run_libs.sh
Labels: approved, lgtm

#146 build: cluster_run_libs.sh: fix typo
  build/root/var/lib/ci-artifacts/entrypoints.d/cluster_run_libs.sh
Labels: approved

#144 nfd_deploy: add hook for OCP 4.5 for finding the CSV
  roles/nfd_deploy/tasks/main.yml
Labels: approved, lgtm

#143 Moving libraries and entitle.sh into /usr/local/bin
  build/root/usr/local/bin/ci_entrypoint_cluster.sh
  build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh
  build/root/usr/local/bin/ci_entrypoint_sro.sh
  build/root/usr/local/bin/entitle.sh
  build/root/usr/local/bin/run
Labels: approved, lgtm

#145 gpu_operator_deploy_from_operatorhub: properly wait for the CSV
  roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_clusterpolicy.yml
Labels: approved, lgtm

#148 gpu_operator_wait_deployment: wait longer for Prometheus to pick up the DCGM metrics
  roles/gpu_operator_wait_deployment/tasks/main.yml
Labels: approved, lgtm, progress/ready-for-review

#152 build/Dockerfile: move helm to the right directory
  build/Dockerfile
Labels: approved, lgtm

#153 entitlement_undeploy: also delete 50-rhsm-repo-ca
  roles/entitlement_undeploy/tasks/main.yml
Labels: approved, lgtm

#147 gpu_operator_run_gpu-burn: improve and store pod description
  roles/gpu_operator_run_gpu-burn/tasks/main.yml
Labels: approved, lgtm, progress/ready-for-review

#155 gpu_operator_wait_deployment: update to support new (>= v1.7.0) GPU Operator validator
  roles/gpu_operator_wait_deployment/tasks/main.yml
Labels: approved, lgtm

#154 build/root/usr/local/bin/entitle.sh: update to use the new CI vault secrets
  build/root/usr/local/bin/entitle.sh
Labels: approved, lgtm

#158 gpu_operator_set_repo-config: fix RHEL 8.4-beta repo-list
  roles/gpu_operator_set_repo-config/tasks/main.yml
Labels: approved, lgtm

#165 Remove RHEL 8.4-beta flags
  CHANGELOG.rst
  build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh
  build/root/usr/local/bin/entitle.sh
  docs/toolbox/gpu_operator.rst
  roles/entitlement_test_wait_deployment/files/entitlement-tester_entrypoint.yml
  roles/gpu_operator_set_repo-config/defaults/main/config.yml
  roles/gpu_operator_set_repo-config/tasks/main.yml
  toolbox/gpu-operator/set_repo-config.sh
Labels: approved, lgtm

#173 gpu_operator_deploy_from_operatorhub: add support for setting the channel
  CHANGELOG.rst
  docs/toolbox/gpu_operator.rst
  roles/gpu_operator_deploy_from_operatorhub/defaults/main/config.yml
  roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml
  roles/gpu_operator_deploy_from_operatorhub/templates/020_operator_sub.yml.j2
  roles/gpu_operator_deploy_from_operatorhub/vars/main/resources.yml
  toolbox/gpu-operator/deploy_from_operatorhub.sh
Labels: approved, lgtm
