Repository openshift-psap/ci-artifacts, pull requests merged in 2022-07, with the labels that each got.

#415 testing: ods: common: properly disable ENABLE_AUTOSCALER
  testing/ods/common.sh
Labels: lgtm, approved

#417 rhods_test_jupyterlab: Add test Pod startup delay
  roles/rhods_test_jupyterlab/defaults/main/config.yml
  roles/rhods_test_jupyterlab/files/entrypoint.sh
  roles/rhods_test_jupyterlab/templates/rhods-ci.yaml
  testing/ods/common.sh
  testing/ods/jh-at-scale.sh
  toolbox/rhods.py
Labels: approved

#418 [cloud-watch] Integrate Route53 hosted zones (for information)
  subprojects/cloud-watch/cleanup-rhods-zombie.py
  subprojects/cloud-watch/ec2.py
Labels: approved

#419 OWNERS: add fcami as approver
  OWNERS
Labels: approved

#429 WIP: RHODS: add zombie cleanup script
  build/Dockerfile
  subprojects/cloud-watch/cleanup-rhods-zombie.py
  subprojects/cloud-watch/ec2.py
  subprojects/cloud-watch/requirements.txt
  testing/ods/common.sh
  testing/ods/zombie_cleanup.sh
Labels: do-not-merge/work-in-progress

#454 cluster_destroy_ocp: allow passing no option to delete the local cluster
  roles/cluster_destroy_ocp/defaults/main/config.yml
  roles/cluster_destroy_ocp/tasks/main.yml
  roles/cluster_destroy_ocp/templates/metadata.json.j2
  toolbox/cluster.py
Labels: lgtm, approved

#457 RHODS: rhods_wait_ods: default: also wait for tensorflow and pytorch images
  roles/rhods_wait_ods/defaults/main/config.yml
Labels: lgtm, approved

#458 testing: run: download the PR and its comment into the artifacts
  testing/run
Labels: approved

#459 testing: run: do not crash when the pull request data cannot be fetched
  testing/run
Labels: lgtm, approved

#460 rhods_deploy_ods: delete the GPU image builds and mock them up
  roles/rhods_deploy_ods/tasks/main.yml
Labels: lgtm, approved

#462 RHODS: use a dedicated image for the artifacts exporter side-car
  roles/rhods_test_jupyterlab/defaults/main/config.yml
  roles/rhods_test_jupyterlab/files/s3-artifacts-exporter.sh
  roles/rhods_test_jupyterlab/tasks/main.yml
  roles/rhods_test_jupyterlab/templates/rhods-ci.yaml
  roles/utils_build_push_image/tasks/build_image.yml
  roles/utils_build_push_image/tasks/main.yml
  roles/utils_build_push_image/templates/image_buildconfig.yml.j2
  testing/ods/common.sh
  testing/ods/images/Containerfile.s3_artifacts_exporter
  testing/ods/jh-at-scale.sh
  toolbox/rhods.py
Labels: approved

#468 RHODS: Fail on notebook errors and define the notebook image in a single location
  roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-run-notebook.robot
  roles/rhods_test_jupyterlab/templates/rhods-ci.yaml
  testing/ods/common.sh
  testing/ods/images/Containerfile.s3_artifacts_exporter
  testing/ods/jh-at-scale.sh
  toolbox/rhods.py
Labels: lgtm, approved
